export const FETCH_TOP_POSTS = 'FETCH_TOP_POSTS';
export const SELECT_POST = 'SELECT_POST';
export const READ_POST = 'READ_POST';
export const DISMISS_POST = 'DISMISS_POST';
export const DISMISS_ALL_POSTS = 'DISMISS_ALL_POSTS';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';